# Generated by Django 5.2.8 on 2025-12-01 03:35

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dineres', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dish',
            name='description',
            field=ckeditor.fields.RichTextField(max_length=255),
        ),
    ]
