# Generated by Django 5.2.8 on 2025-12-27 06:38

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dineres', '0003_remove_dishdetail_unit_ingredient_unit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='review_at',
        ),
        migrations.AlterField(
            model_name='dish',
            name='price',
            field=models.DecimalField(db_index=True, decimal_places=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='dishdetail',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Chờ xử lý'), ('done', 'Hoàn thành'), ('paid', 'Đã thanh toán'), ('cancel', 'Hủy')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='review',
            name='dish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='dineres.dish'),
        ),
    ]
