# Generated by Django 5.2.8 on 2025-12-28 15:22

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dineres', '0004_remove_review_review_at_alter_dish_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Combo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='dishdetail',
            name='dish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dish_details', to='dineres.dish'),
        ),
        migrations.CreateModel(
            name='ComboDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('combo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dineres.combo')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='dineres.dish')),
            ],
            options={
                'unique_together': {('dish', 'combo')},
            },
        ),
        migrations.AddField(
            model_name='combo',
            name='dishes',
            field=models.ManyToManyField(through='dineres.ComboDetail', to='dineres.dish'),
        ),
    ]
