# Generated by Django 5.2.8 on 2026-01-02 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dineres', '0007_ingredienttype_ingredient_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='chef',
            name='experience',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='chef',
            name='specialty',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
