# Generated by Django 5.2.8 on 2026-01-05 05:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dineres', '0008_chef_experience_chef_specialty'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='dineres.booking'),
        ),
        migrations.AddField(
            model_name='order',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Đang chờ'), ('confirmed', 'Đã xác nhận'), ('dining', 'Đang dùng bữa'), ('completed', 'Đã dùng bữa'), ('cancelled', 'Đã hủy')], default='pending', max_length=12),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(choices=[('gram', 'Gram'), ('ml', 'Milliliter'), ('kg', 'Kilogram'), ('spoon', 'Thìa'), ('piece', 'Cái/Quả')], default='gram', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
    ]
