# Generated by Django 5.2.8 on 2026-01-05 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dineres', '0008_chef_experience_chef_specialty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(choices=[('gram', 'Gram'), ('ml', 'Milliliter'), ('kg', 'Kilogram'), ('spoon', 'Thìa'), ('piece', 'Cái/Quả')], default='gram', max_length=50),
        ),
    ]
