# Generated by Django 5.2.8 on 2026-01-07 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dineres', '0009_order_booking_order_staff_alter_booking_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_date']},
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('confirmed', 'Đã xác nhận'), ('dining', 'Đang dùng bữa'), ('completed', 'Đã dùng bữa'), ('cancelled', 'Đã hủy')], default='confirmed', max_length=12),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_role',
            field=models.CharField(choices=[('admin', 'Quản trị viên'), ('customer', 'Khách hàng'), ('staff', 'Nhân viên'), ('chef', 'Đầu bếp')], default='customer', max_length=10),
        ),
    ]
