# Generated by Django 5.2.8 on 2026-01-13 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dineres', '0010_alter_order_options_alter_booking_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dish',
            options={'permissions': [('view_dish_statistics', 'Can view dish revenue statistics')]},
        ),
    ]
