# Generated by Django 5.2.8 on 2026-01-16 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dineres', '0011_alter_dish_options'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterUniqueTogether(
                    name='combodetail',
                    unique_together=None,
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RemoveField(
                    model_name='combodetail',
                    name='combo',
                ),
                migrations.RemoveField(
                    model_name='combodetail',
                    name='dish',
                ),
                migrations.RemoveField(
                    model_name='ingredient',
                    name='type',
                ),
                migrations.RemoveField(
                    model_name='category',
                    name='description',
                ),
                migrations.RemoveField(
                    model_name='dish',
                    name='is_available',
                ),
            ],
        ),
        migrations.DeleteModel(
            name='ComboDetail',
        ),
        migrations.DeleteModel(
            name='Combo',
        ),
        migrations.DeleteModel(
            name='IngredientType',
        ),
    ]
